lang: ja
title: Yabuki Taro's Home Page
author: Yabuki Taro
email: taro.yabuki at gmail dot com
description: 2024/03 更新
github_username: taroyabuki
twitter_username: yabuki
facebook_username: taro.yabuki
instagram_username: taroyabuki
rss: rss
theme: minima
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /:year/:month/:day/:title/
#disqus:
#  shortname: taroyabuki
defaults:
  -
    scope:
      path: "_posts"
    values:
      author: Yabuki Taro
      comments: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
